version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - apt-get update -y
      - apt-get install -y docker
      - npm install -g @nestjs/cli
      - npm install

  pre_build:
    commands:
      - echo Running Prisma migrations...
      - npx prisma generate
      - npx prisma migrate deploy

  build:
    commands:
      - echo Building Docker image...
      - docker build -t kkuk-kkuk-be .
      - docker save kkuk-kkuk-be | gzip > kkuk-kkuk-be.tar.gz

  post_build:
    commands:
      - echo Preparing artifacts for CodeDeploy...
      - mkdir -p output
      - mv kkuk-kkuk-be.tar.gz output/
      - cp appspec.yml output/
      - cp deploy.sh output/
      - cp ./Dockerfile output/

artifacts:
  files:
    - output/**
